### PR TITLE
Add chart for CLusterRoleBinding resource

### PR DESCRIPTION
**Pull request by chapipo**
Add helm chart to instantiate ClusterRoleBinding Kubernetes resource.

### CODE REVIEW

**Comment by ameijer** [comment]
hi @chapipo, thank you so much for your contribution!  This code itself looks good, however, I can't help but notice the high amount of duplication between this and the RoleBinding Resource. I am debating whether we should combine them into a single chart, then using a ternary to update the `kind` or refactoring the common parts up into the library chart `lib-k8s-as-helm`. Do you have any thoughts/ideas/input on the matter?

**Comment by chapipo** [comment]
I have the same feeling about code duplication.

Maybe the refactoring of common parts into the `lib-k8s-as-helm` is more future proof ? In case of addition of some parameters of only one resource (like `aggregationRule` being present in `ClusterRole` but not `Role`)?

**Comment by ameijer** [comment]
Yes, that is a good point about support for minor differences. Library chart would probably be the better move.

**Comment by chapipo** [comment]
Ok ! I will update all charts soon !

**Comment by ameijer** [comment]
Amazing. Thank you again so much!

**Comment by chapipo** [comment]
Superseed by #30

**Pull request closed without merging**
